akademia-envelo-3/meetek-back

src/main/java/pl/envelo/meetek/model/user/StandardUser.java

StandardUser constructor corrected. Due to an error, it was not possible to give the user a name, surname, role and password

Bt001   feat create model classes

---

pom.xml
src/main/java/pl/envelo/meetek/service/DtoMapperService.java

BO096 - feat: add modelMapperService

---

README.md
pom.xml
src/main/java/pl/envelo/meetek/config/SwaggerConfig.java
src/main/resources/application-dev.yml

Swagger implementation corrected. Changes:
- SwaggerUI path changed
- Removed unnecessary dependencies in pom.xml
- Removed unnecessary dependencies in SwaggerConfig class

BT017 - config: swagger configuration

---

src/main/java/pl/envelo/meetek/MeetekApplication.java
src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/service/DtoMapperService.java
src/main/java/pl/envelo/meetek/service/event/SingleEventService.java

Task finished. 
- methods changed to public from private
- method `getSingleEventById` implemented
- REST method `getEvent` implemented
- API documentation finished

BT018   feat get event

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/repository/event/SingleEventRepo.java
src/main/java/pl/envelo/meetek/service/event/SingleEventService.java

Adding method getAllPublicPastNotAcceptedEvents() in the SingleEventService and SingleEventController. Modyfying SQL queries in SingleEventRepo.

BT014 - feat: get events user past public not accepted

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/repository/event/SingleEventRepo.java
src/main/java/pl/envelo/meetek/service/event/SingleEventService.java

Adding methods to SingleEventController and SingleEventService and Query to SingleEventRepo

BT010 - feat: get events - user, future, owned

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/repository/event/SingleEventRepo.java
src/main/java/pl/envelo/meetek/service/event/SingleEventService.java

Adding findAllPastAcceptedByUser() method in SingleEventRepo and getAllPastAcceptedEvents() method in SingleEventService and SingleEventController.

BT011 - feat: get events - user, past, accepted

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/repository/event/SingleEventRepo.java
src/main/java/pl/envelo/meetek/service/event/SingleEventService.java
src/main/resources/application.yml

Task finished, correction in previous methods, changed version of app

BT009 - feat: get events - user, past, owned

---

src/main/java/pl/envelo/meetek/controller/CategoryController.java
src/main/java/pl/envelo/meetek/repository/CategoryRepo.java
src/main/java/pl/envelo/meetek/service/CategoryService.java
src/main/resources/db_init.sql

Creating method getCategories() in CategoryController. Creating method getAllActiveCategories() in CategoryService. Creating method findAllByIsActiveOrderByName() in CategoryRepository. Adding entries to test database file.

BT072 - feat: get active categories

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/service/comment/EventCommentService.java
src/main/resources/db_init.sql

Adding CRUD methods relatedo to event comments  to EventCommentService and SingleEventController

BT035 - feat: CRUD comments

---

src/main/java/pl/envelo/meetek/controller/HashtagController.java
src/main/java/pl/envelo/meetek/repository/HashtagRepo.java
src/main/java/pl/envelo/meetek/service/HashtagService.java

Added method getActiveHashtags() to AdminController, HashtagService, HashtagRepo

BT075   feat get active hashtags

---

src/main/java/pl/envelo/meetek/controller/CategoryController.java
src/main/java/pl/envelo/meetek/model/Category.java
src/main/java/pl/envelo/meetek/service/CategoryService.java

Implementing get, create and edit methods for Category.

BT071 - feat: CRUD category

---

src/main/java/pl/envelo/meetek/service/AttachmentService.java

Adding CRUD methods to AttachmentServiceService

BT039 - feat: CRUD attachment

---

src/main/java/pl/envelo/meetek/service/CoordinatesService.java

Addint CRUD methods to CoordinatesService

BT041 - feat: CRUD coordinates

---

src/main/java/pl/envelo/meetek/controller/group/SectionController.java
src/main/java/pl/envelo/meetek/model/group/Group.java
src/main/java/pl/envelo/meetek/model/group/Section.java
src/main/java/pl/envelo/meetek/service/group/SectionService.java
src/main/java/pl/envelo/meetek/service/user/StandardUserService.java

BT053 - feat: edit section - user, all

---

src/main/java/pl/envelo/meetek/controller/HashtagController.java
src/main/java/pl/envelo/meetek/model/Hashtag.java
src/main/java/pl/envelo/meetek/repository/HashtagRepo.java
src/main/java/pl/envelo/meetek/service/HashtagService.java

Added CRUD methods to HashtagController, HashtagService, HashtagRepo.

BT074_-_feat_CRUD_hashtag

---

src/main/java/pl/envelo/meetek/repository/notification/EventNotificationRepo.java
src/main/java/pl/envelo/meetek/service/notification/EventNotificationService.java

Adding CRUD methods to EventNotificationService

BT085 - feat: CRUD event notification

---

src/main/java/pl/envelo/meetek/controller/user/GuestController.java
src/main/java/pl/envelo/meetek/service/user/GuestService.java

Adding CRUD methods to GuestServiceService and GuestController

BT084 - feat: CRUD guest

---

src/main/java/pl/envelo/meetek/service/notification/CommentNotificationService.java

Adding CRUD methods to CommentNotificationService

BT089 - feat: CRUD comment notification

---

src/main/java/pl/envelo/meetek/model/event/RecurringEventSet.java
src/main/java/pl/envelo/meetek/service/event/RecurringEventSetService.java

added methods to create in RecurringEventSet

BT067 - feat: create recurring event set

---

src/main/java/pl/envelo/meetek/controller/group/SectionController.java
src/main/java/pl/envelo/meetek/model/group/Section.java
src/main/java/pl/envelo/meetek/repository/group/SectionRepo.java
src/main/java/pl/envelo/meetek/service/group/SectionService.java

Added method getAllOwnedSections to SectionController, SectionService, SectionRepo.

BT050  feat get owned sections

---

src/main/java/pl/envelo/meetek/controller/group/SectionController.java
src/main/java/pl/envelo/meetek/service/group/SectionService.java

BT052 - feat: create section

---

src/main/java/pl/envelo/meetek/controller/group/SectionController.java
src/main/java/pl/envelo/meetek/model/group/Section.java
src/main/java/pl/envelo/meetek/repository/group/SectionRepo.java
src/main/java/pl/envelo/meetek/service/group/SectionService.java

added methods in SectionRepo/SectionService/SectionController and changed relation in Section

BT049 - feat: get joined sections

---

src/main/java/pl/envelo/meetek/controller/category/CategoryController.java
src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/controller/user/AdminController.java
src/main/java/pl/envelo/meetek/dto/event/SingleEventShortDto.java
src/main/java/pl/envelo/meetek/dto/group/SectionLongDto.java
src/main/java/pl/envelo/meetek/dto/group/SectionShortDto.java
src/main/java/pl/envelo/meetek/model/group/Section.java
src/main/java/pl/envelo/meetek/service/category/CategoryService.java
src/main/java/pl/envelo/meetek/service/event/SingleEventService.java
src/main/java/pl/envelo/meetek/service/group/SectionService.java
src/main/resources/db_init.sql

BT103 - refact: category, dto, eventService changes

BT103 - refact: category, dto, eventService changes

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/controller/group/SectionController.java
src/main/java/pl/envelo/meetek/controller/user/AdminController.java

Bt099   refact controllers refactoring

---

src/main/java/pl/envelo/meetek/service/event/SingleEventService.java

BT027 - feat: add survey

---

src/main/java/pl/envelo/meetek/repository/survey/SurveyChoiceRepo.java
src/main/java/pl/envelo/meetek/service/survey/SurveyChoiceService.java
src/main/java/pl/envelo/meetek/service/survey/SurveyService.java

BT031 - feat: add survey choice

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java

Adding methods to create comments in SingleEventController.

BT034 - feat: add comment to event

---

src/main/java/pl/envelo/meetek/controller/event/SingleEventController.java
src/main/java/pl/envelo/meetek/service/comment/EventCommentService.java

added methods in EventCommentService, SingleEventController

BT036 - feat: reply to comment

---

src/main/java/pl/envelo/meetek/service/event/SingleEventService.java

Adding method to change number of hashtag's usages.

BT077 - feat: change counter of hashtag

---

src/main/java/pl/envelo/meetek/domain/category/CategoryController.java
src/main/java/pl/envelo/meetek/domain/category/CategoryService.java
src/main/java/pl/envelo/meetek/domain/category/CategoryValidator.java
src/main/java/pl/envelo/meetek/domain/request/CategoryRequestService.java
src/main/java/pl/envelo/meetek/exceptions/DuplicateException.java
src/main/java/pl/envelo/meetek/exceptions/GlobalExceptionHandler.java
src/main/java/pl/envelo/meetek/utils/ValidatorService.java

Creating CategoryValidator and DuplicateException, modifying CategoryController and CategoryService.

BT095 - validation and dto conversion changes for Category

---

src/main/java/pl/envelo/meetek/domain/group/SectionController.java
src/main/java/pl/envelo/meetek/domain/group/SectionService.java
src/main/resources/db_init.sql

Modifying SectionService and SectionController.

BT055 - section deactivation

---

src/main/java/pl/envelo/meetek/domain/group/SectionController.java
src/main/java/pl/envelo/meetek/domain/group/SectionService.java
src/main/java/pl/envelo/meetek/domain/group/SectionValidator.java

Modifying Section Controller, Service and Validator.

BT057/58 - feat: join and leave section

---

Dockerfile

BT113 - feat: docker
